// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SIAO.Controls {
	
	
	public partial class wucListaUsers {
		
		protected System.Web.UI.WebControls.MultiView mvwUsers;
		
		protected System.Web.UI.WebControls.View vwUserList;
		
		protected System.Web.UI.WebControls.Label lblNome;
		
		protected System.Web.UI.WebControls.TextBox txtNome;
		
		protected System.Web.UI.WebControls.Button btnMostrarTodos;
		
		protected System.Web.UI.WebControls.Button btnFiltro;
		
		protected System.Web.UI.WebControls.GridView gvwUsers;
		
		protected System.Web.UI.WebControls.Literal ltlName;
		
		protected System.Web.UI.WebControls.Literal ltlEmail;
		
		protected System.Web.UI.WebControls.Literal ltlTipo;
		
		protected System.Web.UI.WebControls.Literal ltlExpirationDate;
		
		protected System.Web.UI.WebControls.Literal ltlInactive;
		
		protected System.Web.UI.WebControls.Button btnNovo;
		
		protected System.Web.UI.WebControls.View vwUserCadastro;
		
		protected System.Web.UI.UserControl wucCadastroUser1;
	}
}
