// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SIAO {
	
	
	public partial class Logon {
		
		protected System.Web.UI.HtmlControls.HtmlForm frmLogon;
		
		protected System.Web.UI.WebControls.TextBox txtNome;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvNome;
		
		protected System.Web.UI.WebControls.TextBox txtSenha;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvSenha;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Label lblVersion;
		
		protected System.Web.UI.WebControls.ValidationSummary vsmLogin;
	}
}
