// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SIAO.Controls {
	
	
	public partial class wucCadastroUser {
		
		protected System.Web.UI.WebControls.Panel Panel1;
		
		protected System.Web.UI.WebControls.TextBox txtNome;
		
		protected System.Web.UI.WebControls.Label lblN;
		
		protected System.Web.UI.WebControls.TextBox txtAcsName;
		
		protected System.Web.UI.WebControls.Label lblAN;
		
		protected System.Web.UI.WebControls.TextBox txtSenha;
		
		protected System.Web.UI.WebControls.Label lblS;
		
		protected System.Web.UI.WebControls.TextBox txtCfrSenha;
		
		protected System.Web.UI.WebControls.Label lblCS;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Label lblE;
		
		protected System.Web.UI.WebControls.TextBox txtValidade;
		
		protected System.Web.UI.WebControls.Label lblV;
		
		protected System.Web.UI.WebControls.Calendar txtValidade_CalendarExtender;
		
		protected System.Web.UI.WebControls.DropDownList ddlAcess;
		
		protected System.Web.UI.WebControls.Label lblAcs;
		
		protected System.Web.UI.WebControls.CheckBox cbxAtivo;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell tdNA;
		
		protected System.Web.UI.WebControls.DropDownList ddlNivel;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
