// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SIAO.Controls {
	
	
	public partial class wucFilter {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dvFilter;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dvFiltro;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dvRedes;
		
		protected System.Web.UI.WebControls.DropDownList ddlRedesRelatorios;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl dvLoja;
		
		protected System.Web.UI.WebControls.DropDownList ddlLojaRelatorios;
		
		protected System.Web.UI.WebControls.RadioButton rbtPeriodo;
		
		protected System.Web.UI.WebControls.TextBox txtInicio;
		
		protected System.Web.UI.WebControls.TextBox txtFim;
		
		protected System.Web.UI.WebControls.RadioButton rbtMes;
	}
}
